export default {
  ts: "TypeScript",
  js: "JavaScript",
  python: "Python",
  rust: "Rust",
  postgreSql: "PostgreSQL",
  mongo: "MongoDB",
  mySql: "MySQL",
  sqlite: "SQLite",
  html: "HTML",
  css: "CSS",
  tailwindCss: "TailwindCSS",
  shadcn: "ShadcnUI",
  node: "Node.js",
  bun: "Bun",
  cursor: "Cursor",
  vscode: "VSCode",
  git: "Git & GitHub",
  docker: "Docker",
  cicd: "CI/CD",
  supabase: "Supabase",
  firebase: "Firebase",
  vercel: "Vercel",
  netlify: "Netlify",
  react: "React",
  nextJs: "Next.js",
  vue: "Vue",
  flask: "Flask",
  express: "Express",
  hono: "Hono",
  reactQuery: "ReactQuery",
  zod: "Zod",
  valibot: "Valibot",
};
